name: Update Version and Create Release

on:
  push:
    branches:
      - beta
      - staging
      - production

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install json sys requests re os zipfile hashlib

    - name: Bundle Files
      run: |
        zip Carbon-Official-Egg.zip egg-rust--all-carbon-builds.json README.md
      
    - name: Compare and Release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACTION_TOKEN }}
      run: python .github/scripts/update_version.py